### ISSUE TITLE
佬，能提供一份用于rk3566板子的rknn模型吗？

### ISSUE THREAD

**Issue by yanshuangyingying** [cqu20160901/MiDaS_DepthEstimation_rknn_Cplusplus#1]

**Comment by cqu20160901** [comment]
看readme，里面有模型路径。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月28日(周六) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cqu20160901/MiDaS_DepthEstimation_rknn_Cplusplus] 佬，能提供一份用于rk3566板子的rknn模型吗？ (Issue #1)

**Comment by yanshuangyingying** [comment]
> 看readme，里面有模型路径。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月28日(周六) 下午3:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cqu20160901/MiDaS_DepthEstimation_rknn_Cplusplus] 佬，能提供一份用于rk3566板子的rknn模型吗？ (Issue #1) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

你那个模型是3588板子的，我自己转了一个但是效果不怎么好，这和量化用的数据集关系大吗？图片就是你那张测试用图
![test_depth](https://github.com/user-attachments/assets/14ff33be-8a7d-465c-ba8a-37a2a0837f36)
